refactor vbox script

diff --git a/vboxsetup b/vboxsetup
--- a/vboxsetup
+++ b/vboxsetup
@@ -1,5 +1,30 @@
 #!/usr/bin/env bash
 
+function checksudo {
+	if [[ $(id --user) != 0 ]]
+	then
+		echo 'You are not running as root. Re-run with sudo.'
+		exit 1
+	fi
+}
+
+function checkcompatibility {
+	# X -version sends to stderr rather than stdout, so |& is necessary to pipe it
+	current_xserver_version=$(X -version |& grep 'X Server' | grep --only-matching --extended-regexp '([0-9]+(\.)?)+')
+	supported_xserver_version='1.15.1'
+	
+	if [[ "${current_xserver_version}" != "${supported_xserver_version}" ]]
+	then
+		echo "Unless you have taken special action, the HOST Ubuntu system is likely running the default Ubuntu repository version of Virtualbox."
+		echo "Currently, this version of Virtualbox on the HOST only supports X Server version $supported_xserver_version on GUEST systems."
+		echo "This system (the GUEST) has X Server version $current_xserver_version."
+		echo "This matters because the script will configure Virtualbox on the GUEST to allow full-screen. This fails due to X Server incompatability."
+		echo "Ubuntu 14.04.1 comes with the supported version of X Server; Ubuntu 14.04.2 and later do not."
+		echo "Please run this script on a clean Ubuntu 14.04.1 version."
+		exit 1
+	fi
+}
+
 function install {
 	stepname='installing virtualbox-guest-dkms'
 	vbox_guest='virtualbox-guest-dkms'
@@ -33,31 +58,11 @@ function earlyexit {
 	exit 1
 }
 
-if [[ $(id --user) != 0 ]]
-then
-	echo 'You are not running as root. Re-run with sudo.'
-	exit 1
-fi
-
-# X -version sends to stderr rather than stdout, so |& is necessary to pipe it
-current_xserver_version=$(X -version |& grep 'X Server' | grep --only-matching --extended-regexp '([0-9]+(\.)?)+')
-supported_xserver_version='1.15.1'
-
-if [[ "${current_xserver_version}" != "${supported_xserver_version}" ]]
-then
-	echo "Unless you have taken special action, the HOST Ubuntu system is likely running the default Ubuntu repository version of Virtualbox."
-	echo "Currently, this version of Virtualbox on the HOST only supports X Server version $supported_xserver_version on GUEST systems."
-	echo "This system (the GUEST) has X Server version $current_xserver_version."
-	echo "This matters because the script will configure Virtualbox on the GUEST to allow full-screen. This fails due to X Server incompatability."
-	echo "Ubuntu 14.04.1 comes with the supported version of X Server; Ubuntu 14.04.2 and later do not."
-	echo "Please run this script on a clean Ubuntu 14.04.1 version."
-	exit 1
-fi
-
 logfile="${HOME}/${0}.log"
 sudo rm --force $logfile
 
-preinstall
+checksudo
+checkcompatibility
 install
 
 exit 0
